
service: nodejs-github-search-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: server/server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'